import test from 'node:test';
import assert from 'node:assert/strict';
import {createDefault,clone,makeItem,wallLength} from '../app/planner/model';
import {spaces,resizeBuilding,itemBounds} from '../app/planner/geometry';
import {createProgramme,programmeTotals,placedProgramme,spaceMode,SPACE_PURPOSES} from '../app/planner/salesOffice';
import {insertSpace,transformSpace,removeSpace,moduleDimensions,moduleFurniture} from '../app/planner/spaceModules';
import {projectSchema} from '../app/planner/validation';
const close=(a:number,b:number,tol=.0001)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
const blank=()=>{const p=createDefault();p.walls=[];p.openings=[];p.furniture=[];p.tags=[];p.programme=createProgramme(600);return p};
test('source programme reconciles all groups, net and reserve',()=>{
 for(const [format,groups] of [[200,[61,48,14,37]],[400,[117,98,50,55]],[600,[170,155,73,82]]] as const){const p=createProgramme(format),t=programmeTotals(p);assert.deepEqual(t.groups.map(g=>g.area),groups);close(t.net,format*.8);close(t.gross,format);close(t.reserve,format*.2);assert.equal(p.items.length,28);assert.ok(projectSchema.safeParse({...blank(),programme:p}).success)}
 assert.equal(createProgramme(600).items.find(r=>r.purposeId==='sales-office')!.quantity,5);assert.equal(createProgramme(600).items.find(r=>r.purposeId==='bank')!.quantity,2);assert.equal(createProgramme(200).items.find(r=>r.purposeId==='signing')!.quantity,0);assert.equal(spaceMode('archive',200),'niche');
});
test('all included preset modules fit their own bounds and validate',()=>{
 for(const format of [200,400,600] as const){const p=blank();p.programme=createProgramme(format);for(const row of p.programme.items.filter(r=>r.quantity)){const {project,space:z}=insertSpace(p,row.purposeId,{x:15,y:6},0);assert.ok(projectSchema.safeParse(project).success,`${format} ${row.purposeId}`);close(z.w*z.d,row.unitArea,.01);for(const f of project.furniture){const b=itemBounds(f);assert.ok(b.x>=z.x&&b.y>=z.y&&b.x+b.w<=z.x+z.w&&b.y+b.h<=z.y+z.d, f.name)}if(row.purposeId!=='entry')assert.ok(project.furniture.length>0, row.purposeId);if(z.enclosed)close(spaces(project,0).find(r=>r.id===z.id)!.area,z.w*z.d)}}
});
test('insertion preserves input and creates exact clear dimensions, attached door, programme',()=>{
 const p=blank();delete p.programme;const original=clone(p),{project:q,space:z}=insertSpace(p,'sales-office',{x:7,y:4},0);assert.deepEqual(p,original);assert.equal(q.walls.length,4);assert.equal(q.openings.length,1);assert.equal(q.furniture.length,5);assert.equal(q.programme?.format,600);assert.ok(q.walls.some(w=>w.id===q.openings[0].wallId));close(spaces(q,0).find(r=>r.id===z.id)!.area,z.w*z.d);assert.equal(placedProgramme(q).length,1);
});
test('open waiting zone adds no physical room and does not duplicate gross area',()=>{const p=blank(),{project:q,space:z}=insertSpace(p,'waiting',{x:16,y:5},0);assert.equal(q.walls.length,0);assert.equal(q.tags.length,0);assert.equal(q.openings.length,0);close(spaces(q,0)[0].area,spaces(p,0)[0].area);assert.equal(placedProgramme(q).length,1);assert.equal(z.enclosed,false)});
test('move and resize carry walls, doors, tags and items without stretching furniture',()=>{
 const {project:p,space:z}=insertSpace(blank(),'sales-office',{x:7,y:4},0),q=transformSpace(p,z.id,{x:z.x+3,y:z.y+.5,w:z.w+1,d:z.d+.5});assert.equal(q.furniture.length,p.furniture.length);for(const f of q.furniture){const old=p.furniture.find(v=>v.id===f.id)!;assert.deepEqual([f.w,f.d,f.h],[old.w,old.d,old.h])}const next=q.plannedSpaces![0];close(spaces(q,0).find(r=>r.id===z.id)!.area,next.w*next.d);assert.equal(q.openings[0].width,p.openings[0].width);const door=q.openings[0],wall=q.walls.find(w=>w.id===door.wallId)!;assert.ok(door.offset>=0&&door.offset+door.width<wallLength(wall));assert.ok(projectSchema.safeParse(q).success);const scaled=resizeBuilding(q,44,14),r=scaled.plannedSpaces![0];close(spaces(scaled,0).find(r=>r.id===z.id)!.area,r.w*r.d);
});
test('bounds, furniture, upper slab, overlapping modules and locks block invalid operations atomically',()=>{
 const p=blank();assert.throws(()=>insertSpace(p,'sales-office',{x:1,y:1},0));assert.throws(()=>insertSpace(p,'sales-office',{x:5,y:5},1));p.furniture.push(makeItem('stair',34,6,1));assert.throws(()=>insertSpace(p,'sales-office',{x:34,y:6},1));const {project:q,space:z}=insertSpace(blank(),'sales-office',{x:7,y:4},0),before=clone(q);assert.throws(()=>insertSpace(q,'waiting',{x:7,y:4},0));assert.deepEqual(q,before);assert.throws(()=>transformSpace(q,z.id,{...z,w:1}));q.furniture[0].locked=true;assert.throws(()=>transformSpace(q,z.id,{...z,x:z.x+1}));assert.throws(()=>removeSpace(q,z.id));assert.ok(removeSpace(q,z.id,true).furniture[0].locked);
});
test('deleting removes attached geometry; dissolving retains editable elements and room function',()=>{const {project:p,space:z}=insertSpace(blank(),'sales-office',{x:7,y:4},0),removed=removeSpace(p,z.id);assert.equal(removed.walls.length,0);assert.equal(removed.openings.length,0);assert.equal(removed.furniture.length,0);assert.equal(removed.tags.length,0);const dissolved=removeSpace(p,z.id,true);assert.equal(dissolved.plannedSpaces!.length,0);assert.equal(dissolved.walls.length,4);assert.equal(dissolved.openings.length,1);assert.ok(dissolved.furniture.every(f=>!f.group));assert.equal(placedProgramme(dissolved).length,1)});
test('existing tagged rooms count by assignment; disabled upper floor is excluded',()=>{const p=createDefault(),r=spaces(p,0).find(r=>r.tag)!;r.tag!.purposeId='sales-office';const rows=placedProgramme(p);assert.equal(rows.length,1);close(rows[0].area,r.area);const {project:q}=insertSpace(blank(),'director',{x:35,y:4},1);assert.equal(placedProgramme(q).length,1);q.mezzanine.enabled=false;assert.equal(placedProgramme(q).length,0)});
test('old files remain valid; malformed programme fields are rejected',()=>{assert.ok(projectSchema.safeParse(createDefault()).success);const p=blank();p.programme!.items[0].purposeId='unknown';assert.equal(projectSchema.safeParse(p).success,false);p.programme=createProgramme(600);p.programme.items[0].quantity=NaN;assert.equal(projectSchema.safeParse(p).success,false);p.programme=createProgramme(600);p.programme.items[1].purposeId=p.programme.items[0].purposeId;assert.equal(projectSchema.safeParse(p).success,false)});
