'use client';
import {useRef,useState,useEffect,useImperativeHandle,forwardRef} from 'react';
import {Project,Point,Wall,Furniture,Opening,shell,mm,clone,round,uid,wallLength} from './model';
import {Space,moveWall,resizeBuilding,openingPosition} from './geometry';
import Symbol from './Symbol';
import {transformSpace,moduleDimensions} from './spaceModules';
import {programmeFor,purpose} from './salesOffice';
import type {PlannedSpace} from './programmeTypes';
import OpeningSymbol from './OpeningSymbol';
import {useSpacePan} from './useSpacePan';
import type {LibraryDrop,ClientPoint} from './useLibraryDrag';
import {zoomAt,panBy,wheelAction,type NavigationMode} from './navigation';
import {openingForWall,normalizeOpening,decodeOpeningPreset,type WallPreset,type OpeningPreset} from './presets';
export type Selection={type:'item'|'wall'|'opening'|'room'|'building'|'space';id:string}|null;
export type Tool='select'|'wall'|'glass'|'room'|'door'|'window'|'opening'|'pan'|'measure';
export type CanvasAPI={fit:()=>void;zoom:(factor:number)=>void;drop:(payload:LibraryDrop,p:ClientPoint)=>void};
export type CanvasProps={project:Project;level:number;rooms:Space[];selection:Selection;tool:Tool;snap:boolean;labels:boolean;dimensions:boolean;placing:string|null;navigationMode:NavigationMode;wallPreset:WallPreset;openingPreset:OpeningPreset;roomName:string;onZoom:(n:number)=>void;onNotice:(s:string)=>void;onSelect:(s:Selection)=>void;onUpdate:(p:Project)=>void;onBegin:()=>void;onAdd:(id:string,p:Point)=>void;onToolDone:()=>void;onRoom:(s:Space)=>void};
const ACC='#1b8974';
export function WallDrawing({w,openings,selected=false,onDown,onOpening}:{w:Wall;openings:Opening[];selected?:boolean;onDown?:(e:React.PointerEvent)=>void;onOpening?:(e:React.PointerEvent,o:Opening)=>void}){
 const a=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x)*180/Math.PI;
 return <g><line x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke={selected?ACC:w.kind==='glass'?'#9ab9c2':'#34453f'} strokeWidth={w.thickness} strokeLinecap="square"/>{w.kind==='glass'&&<line x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke="#edf5f4" strokeWidth={w.thickness*.45}/>}<line data-wall={w.id} onPointerDown={onDown} x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke="transparent" strokeWidth={Math.max(.28,w.thickness+.12)} style={{cursor:'move'}}/>{openings.map(original=>{const o=normalizeOpening(original,w);return <g key={o.id} data-opening={o.id} transform={`translate(${w.a.x} ${w.a.y}) rotate(${a}) translate(${o.offset} 0)`} onPointerDown={e=>onOpening?.(e,original)} style={{cursor:'move'}}><rect y={-w.thickness/2-.02} width={o.width} height={w.thickness+.04} fill="#f3f0e9"/><OpeningSymbol o={o} width={o.width}/><rect width={o.width} y={-.16} height={.32} fill="transparent"/></g>})}</g>
}
export function Dim({a,b,text,size=.3,offset=.5}:{a:Point;b:Point;text:string;size?:number;offset?:number}){const horizontal=Math.abs(a.y-b.y)<.01;return <g fill="#677c72" stroke="#8da097" strokeWidth={.017} pointerEvents="none">{horizontal?<><path d={`M ${a.x} ${a.y} V ${a.y+offset+.15} M ${b.x} ${b.y} V ${b.y+offset+.15} M ${a.x} ${a.y+offset} H ${b.x}`} fill="none"/>{[a.x,b.x].map(x=><path key={x} d={`M ${x-.1} ${a.y+offset+.1} l .2 -.2`}/>)}<text x={(a.x+b.x)/2} y={a.y+offset-.12} fontSize={size} stroke="none" textAnchor="middle">{text}</text></>:<><path d={`M ${a.x} ${a.y} H ${a.x+offset+.15} M ${b.x} ${b.y} H ${b.x+offset+.15} M ${a.x+offset} ${a.y} V ${b.y}`} fill="none"/><text transform={`translate(${a.x+offset-.12} ${(a.y+b.y)/2}) rotate(-90)`} fontSize={size} stroke="none" textAnchor="middle">{text}</text></>}</g>}
export const PlanCanvas=forwardRef<CanvasAPI,CanvasProps>(function PlanCanvas(props,ref){
 const {project:p,level,rooms,selection,tool,snap,labels,dimensions,placing,navigationMode,wallPreset,openingPreset,roomName,onZoom,onNotice,onSelect,onUpdate,onBegin,onAdd,onToolDone,onRoom}=props;
 const space=useSpacePan(),spaceGhost=useRef<SVGGElement>(null);const placingPurpose=placing?.startsWith('space:')?purpose(placing.slice(6)):undefined;let ghostSize:{w:number;d:number}|undefined;if(placingPurpose)try{ghostSize=moduleDimensions(placingPurpose.id,programmeFor(p).items.find(r=>r.purposeId===placingPurpose.id)?.unitArea||12)}catch{};
 const svg=useRef<SVGSVGElement>(null),drag=useRef<any>(null),[size,setSize]=useState({w:0,h:0,left:0,top:0}),[view,setView]=useState({x:-2,y:-7,w:44,h:26}),[draft,setDraft]=useState<{a:Point;b:Point}|null>(null),[measure,setMeasure]=useState<{a:Point;b:Point}|null>(null);const scale=(size.w||800)/view.w,fs=Math.max(.18,Math.min(.6,12/scale)),handle=Math.max(.07,4/scale);
 const fit=()=>{if(!size.w||!size.h)return;const start=level?p.mezzanine.start:0,w=p.width-start+5,h=Math.max(p.depth+6,w*size.h/size.w),ww=h*size.w/size.h;setView({x:start+(p.width-start-ww)/2,y:(p.depth-h)/2,w:ww,h})};
 useImperativeHandle(ref,()=>({fit,drop:dropAt,zoom:factor=>setView(v=>zoomAt(v,factor,{x:v.x+v.w/2,y:v.y+v.h/2}))}));
 useEffect(()=>{const el=svg.current;if(!el)return;const ob=new ResizeObserver(e=>{const r=e[0].contentRect;const bounds=el.getBoundingClientRect();setSize({w:r.width||800,h:r.height||600,left:bounds.left,top:bounds.top})});ob.observe(el);return()=>ob.disconnect()},[]);
 const previousSize=useRef({w:0,h:0,left:0,top:0});
 useEffect(()=>{if(!size.w||!size.h)return;const prev=previousSize.current;if(!prev.w)fit();else setView(v=>{const w=v.w*size.w/prev.w,h=v.h*size.h/prev.h;return {x:v.x+(size.left-prev.left)*v.w/prev.w,y:v.y+(size.top-prev.top)*v.h/prev.h,w,h}});previousSize.current=size},[size.w,size.h]);
 useEffect(()=>{fit()},[level,p.id]);
 useEffect(()=>{onZoom(Math.round((p.width-(level?p.mezzanine.start:0)+5)/view.w*100))},[view.w,p.width,p.mezzanine.start,level,onZoom]);
 const point=(e:{clientX:number;clientY:number})=>{const m=svg.current?.getScreenCTM();if(!m)return {x:0,y:0};const q=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return {x:q.x,y:q.y}};
 const snapped=(q:Point,exact=false)=>{if(!snap||exact)return q;let x=round(q.x),y=round(q.y);for(const w of[...shell(p,level),...p.walls.filter(w=>w.level===level)])for(const a of[w.a,w.b]){if(Math.abs(a.x-x)<.12)x=a.x;if(Math.abs(a.y-y)<.12)y=a.y;}return {x,y}};
 useEffect(()=>{const el=svg.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();if(drag.current)return;const action=wheelAction(e,navigationMode);if(action.type==='zoom'){const q=point(e);setView(v=>zoomAt(v,action.factor,q))}else setView(v=>panBy(v,action.dx,action.dy,size));};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[view,navigationMode,size]);
 const capture=(e:React.PointerEvent,data:any)=>{e.stopPropagation();svg.current?.setPointerCapture(e.pointerId);drag.current={...data,start:point(e),baseline:clone(p),client:{x:e.clientX,y:e.clientY},view};};
 const downItem=(e:React.PointerEvent,f:Furniture)=>{if(tool!=='select'||placing)return;onSelect({type:'item',id:f.id});if(f.locked){e.stopPropagation();return}capture(e,{type:'item',id:f.id});};
 const insertOpening=(w:Wall,q:Point,preset=openingPreset)=>{const o=openingForWall(w,q,preset,p.openings);if(!o){onNotice('Проём не помещается или пересекает другой. Выберите свободный участок стены.');return}onBegin();onUpdate({...p,openings:[...p.openings,o]});onSelect({type:'opening',id:o.id});onToolDone()};

 const dropAt=(payload:LibraryDrop,client:ClientPoint)=>{const rect=svg.current?.getBoundingClientRect();if(!rect||client.clientX<rect.left||client.clientX>rect.right||client.clientY<rect.top||client.clientY>rect.bottom)return;const q=point(client);if(payload.itemId)onAdd(payload.itemId,snapped(q));else if(payload.opening){const preset=payload.opening;const nearest=[...shell(p,level),...p.walls.filter(w=>w.level===level)].map(w=>{const l=wallLength(w),t=Math.max(0,Math.min(1,((q.x-w.a.x)*(w.b.x-w.a.x)+(q.y-w.a.y)*(w.b.y-w.a.y))/(l*l))),x=w.a.x+t*(w.b.x-w.a.x),y=w.a.y+t*(w.b.y-w.a.y);return {w,d:Math.hypot(q.x-x,q.y-y)}}).sort((a,b)=>a.d-b.d)[0];if(preset&&nearest&&nearest.d<Math.max(.4,12/scale))insertOpening(nearest.w,q,preset);else onNotice('Перетащите проём непосредственно на стену.')}};
 const downSpace=(e:React.PointerEvent,z:PlannedSpace)=>{if(tool!=='select'||placing)return;onSelect({type:'space',id:z.id});capture(e,{type:'space',id:z.id})};
 const downWall=(e:React.PointerEvent,w:Wall)=>{if(['door','window','opening'].includes(tool)){e.stopPropagation();insertOpening(w,point(e));return}if(tool!=='select'||placing)return;if(w.id.startsWith('shell')){e.stopPropagation();onSelect({type:'building',id:'building'});return}const z=p.plannedSpaces?.find(z=>z.id===w.group);if(z){downSpace(e,z);return}onSelect({type:'wall',id:w.id});capture(e,{type:'wall',id:w.id});};
 const rootDown=(e:React.PointerEvent)=>{if(e.button===1||e.button===2||tool==='pan'||space.active.current){capture(e,{type:'pan'});return}const q=snapped(point(e),e.shiftKey);if(placing){onAdd(placing,q);return}if(['wall','glass','room','measure'].includes(tool)){capture(e,{type:tool,origin:q});setDraft({a:q,b:q});return}if(['door','window','opening'].includes(tool)){onNotice('Нажмите на линию стены, чтобы вставить проём.');return}if(tool==='select')onSelect(null);};
 const move=(e:React.PointerEvent)=>{const d=drag.current;if(!d){if(spaceGhost.current&&ghostSize&&placingPurpose){const q=snapped(point(e)),x=q.x-ghostSize.w/2,y=q.y-ghostSize.d/2;spaceGhost.current.style.display='';spaceGhost.current.setAttribute('transform',`translate(${x} ${y})`)}return;}if(d.type!=='pan'&&Math.hypot(e.clientX-d.client.x,e.clientY-d.client.y)<2&&!d.begun)return;if(!d.begun&&d.type!=='pan'&&d.type!=='measure'){d.begun=true;onBegin()}const raw=point(e),q=snapped(raw,e.shiftKey),delta={x:raw.x-d.start.x,y:raw.y-d.start.y},b:Project=d.baseline;
 if(d.type==='pan'){const dx=(e.clientX-d.client.x)*d.view.w/size.w,dy=(e.clientY-d.client.y)*d.view.h/size.h;setView({...d.view,x:d.view.x-dx,y:d.view.y-dy});return}
 if(['wall','glass','room','measure'].includes(d.type)&&!d.id){let end=q;if(d.type==='wall'||d.type==='glass')end=Math.abs(q.x-d.origin.x)>Math.abs(q.y-d.origin.y)?{x:q.x,y:d.origin.y}:{x:d.origin.x,y:q.y};setDraft({a:d.origin,b:end});return}
 if(d.type==='space'||d.type==='space-resize'){const z=b.plannedSpaces!.find(z=>z.id===d.id)!;let rect={x:z.x,y:z.y,w:z.w,d:z.d};const dx=round(delta.x,snap?.05:.001),dy=round(delta.y,snap?.05:.001);if(d.type==='space'){rect.x+=dx;rect.y+=dy}else{const west=d.corner.includes('w'),north=d.corner.includes('n');rect={x:z.x+(west?dx:0),y:z.y+(north?dy:0),w:z.w+(west?-dx:dx),d:z.d+(north?-dy:dy)}}try{onUpdate(transformSpace(b,z.id,rect));d.problem=null}catch(error){d.problem=error instanceof Error?error.message:'Не удалось изменить пространство.'}return}
 if(d.type==='item'){const f=b.furniture.find(f=>f.id===d.id)!;const x=snap?round(f.x+delta.x,e.shiftKey?.01:.05):f.x+delta.x,y=snap?round(f.y+delta.y,e.shiftKey?.01:.05):f.y+delta.y;onUpdate({...b,furniture:b.furniture.map(v=>v.id===f.id||f.group&&!b.plannedSpaces?.some(z=>z.id===f.group)&&v.group===f.group?{...v,x:v.x+x-f.x,y:v.y+y-f.y}:v)});}
 if(d.type==='resize'){const f=b.furniture.find(f=>f.id===d.id)!,angle=f.rotation*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),dx=delta.x*c+delta.y*s,dy=-delta.x*s+delta.y*c,sx=d.corner.includes('w')?-1:1,sy=d.corner.includes('n')?-1:1,w=Math.min(20,Math.max(.1,round(f.w+sx*dx,snap?.05:.001))),dep=Math.min(20,Math.max(.1,round(f.d+sy*dy,snap?.05:.001))),cx=sx*(w-f.w)/2,cy=sy*(dep-f.d)/2;onUpdate({...b,furniture:b.furniture.map(v=>v.id===f.id?{...v,w,d:dep,x:round(f.x+cx*c-cy*s,.001),y:round(f.y+cx*s+cy*c,.001)}:v)});}
 if(d.type==='rotate'){const f=b.furniture.find(f=>f.id===d.id)!,a=Math.atan2(raw.y-f.y,raw.x-f.x)*180/Math.PI+90;onUpdate({...b,furniture:b.furniture.map(v=>v.id===f.id?{...v,rotation:round(a,e.shiftKey?1:15)}:v)});}
 if(d.type==='wall'){const w=b.walls.find(w=>w.id===d.id)!;onUpdate(moveWall(b,w.id,round(Math.abs(w.a.x-w.b.x)<.01?delta.x:delta.y,snap?.05:.001)));}
 if(d.type==='wall-end'){const w=b.walls.find(w=>w.id===d.id)!,vertical=Math.abs(w.a.x-w.b.x)<.01,next=vertical?{x:w.a.x,y:q.y}:{x:q.x,y:w.a.y},other=d.end==='a'?w.b:w.a;if(Math.hypot(next.x-other.x,next.y-other.y)>=.3)onUpdate({...b,walls:b.walls.map(v=>v.id===w.id?{...v,[d.end]:next}:v)});}
 if(d.type==='opening'){const o=b.openings.find(o=>o.id===d.id)!,w=[...shell(b,level),...b.walls].find(w=>w.id===o.wallId)!,l=wallLength(w),offset=o.offset+(delta.x*(w.b.x-w.a.x)+delta.y*(w.b.y-w.a.y))/l;onUpdate({...b,openings:b.openings.map(v=>v.id===o.id?{...v,offset:Math.max(0,Math.min(l-v.width,round(offset,snap?.05:.001)))}:v)});}
 if(d.type==='shell'){let w=b.width,h=b.depth;if(d.edge==='right')w=round(b.width+delta.x,.1);if(d.edge==='left')w=round(b.width-delta.x,.1);if(d.edge==='bottom')h=round(b.depth+delta.y,.1);if(d.edge==='top')h=round(b.depth-delta.y,.1);onUpdate(resizeBuilding(b,Math.min(100,Math.max(5,w)),Math.min(100,Math.max(5,h))));}
 };
 const end=()=>{const d=drag.current;if(!d)return;if(draft&&['wall','glass','room','measure'].includes(d.type)&&!d.id){const {a,b}=draft,len=Math.hypot(a.x-b.x,a.y-b.y);if(d.type==='measure'){setMeasure(draft)}else if(len>.4){const next=clone(p);if(d.type==='room'){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y);if(w>=1&&h>=1){const pts=[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}];const walls=pts.map((a,i)=>({id:uid(),a,b:pts[(i+1)%4],kind:wallPreset.kind,thickness:wallPreset.thickness,height:wallPreset.height,level}));next.walls.push(...walls);next.openings.push({id:uid(),wallId:walls[2].id,offset:(w-Math.min(.9,w-.1))/2,width:Math.min(.9,w-.1),height:Math.min(2.2,wallPreset.height),sill:0,kind:'door',flip:false});next.tags.push({id:uid(),x:x+w/2,y:y+h/2,name:roomName,color:'#e5ebe3',level,notes:''});}}else next.walls.push({id:uid(),a,b,kind:wallPreset.kind,height:wallPreset.height,thickness:wallPreset.thickness,level});onUpdate(next);onToolDone();}}
 if(d.problem)onNotice(d.problem);drag.current=null;setDraft(null);};
 const cancel=()=>{const d=drag.current;if(d&&['item','resize','rotate','wall','wall-end','opening','shell','space','space-resize'].includes(d.type))onUpdate(d.baseline);drag.current=null;setDraft(null)};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')cancel()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 const selectedSpace=selection?.type==='space'?p.plannedSpaces?.find(z=>z.id===selection.id):undefined;
 const selectedItem=selection?.type==='item'?p.furniture.find(f=>f.id===selection.id):null,selectedWall=selection?.type==='wall'?p.walls.find(w=>w.id===selection.id):null;
 const onOpening=(e:React.PointerEvent,o:Opening)=>{if(tool!=='select'||placing)return;onSelect({type:'opening',id:o.id});capture(e,{type:'opening',id:o.id})};
 return <svg ref={svg} tabIndex={0} className={`plan-svg tool-${tool}${space.held?' space-pan':''}`} viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`} onPointerDownCapture={e=>{if(e.button===1||e.button===2||tool==='pan'||space.active.current){e.preventDefault();capture(e,{type:'pan'})}}} onPointerDown={rootDown} onPointerMove={move} onPointerLeave={()=>{if(spaceGhost.current)spaceGhost.current.style.display='none'}} onPointerUp={end} onPointerCancel={cancel} onContextMenu={e=>e.preventDefault()} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDrop={e=>{e.preventDefault();dropAt({itemId:e.dataTransfer.getData('application/x-office-item')||undefined,opening:decodeOpeningPreset(e.dataTransfer.getData('application/x-office-opening'))||undefined},e)}} aria-label="План офиса: перетаскивайте предметы и стены">
 <defs><pattern id="plan-grid" width={1} height={1} patternUnits="userSpaceOnUse"><path d="M 1 0 H 0 V 1" fill="none" stroke="#a8b7ae" strokeOpacity={.3} strokeWidth={.01}/></pattern></defs>
 {level===1&&<g><rect width={p.mezzanine.start} height={p.depth} fill="#e4e8e1" opacity={.35}/><text x={p.mezzanine.start/2} y={p.depth/2} textAnchor="middle" fontSize={fs*1.3} fill="#87958c">Второй свет · перекрытия нет</text></g>}
 <rect x={level?p.mezzanine.start:0} width={level?p.width-p.mezzanine.start:p.width} height={p.depth} fill="#edece4"/>
 {rooms.map(s=><g key={s.id} onPointerDown={e=>{if(tool==='select'&&!placing){e.stopPropagation();onRoom(s)}}}>{s.rects.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.w+.0005} height={r.h+.0005} fill={s.color} stroke={selection?.id===s.id?ACC:undefined} strokeWidth={.008}/>)}</g>)}
 {(p.plannedSpaces||[]).filter(z=>z.level===level).map(z=><g key={z.id} data-space={z.id} onPointerDown={e=>downSpace(e,z)} style={{cursor:tool==='select'?'move':undefined}}><rect x={z.x} y={z.y} width={z.w} height={z.d} fill={z.color} fillOpacity={z.enclosed?.18:.75} stroke={selection?.id===z.id?ACC:'#82978b'} strokeWidth={.045} strokeDasharray={z.enclosed?undefined:'.18 .12'}/></g>)}
 {snap&&<rect x={level?p.mezzanine.start:0} width={level?p.width-p.mezzanine.start:p.width} height={p.depth} fill="url(#plan-grid)" pointerEvents="none"/>}
 {p.furniture.filter(f=>f.level===level).sort((a,b)=>(a.kind==='rug'?-1:0)-(b.kind==='rug'?-1:0)).map(f=><g key={f.id} data-item={f.id} transform={`translate(${f.x} ${f.y}) rotate(${f.rotation})`} onPointerDown={e=>downItem(e,f)} style={{cursor:f.locked?'not-allowed':'move'}}><Symbol item={f} detail={scale>20}/><rect x={-f.w/2} y={-f.d/2} width={f.w} height={f.d} fill="transparent"/></g>)}
 {[...p.walls.filter(w=>w.level===level),...shell(p,level)].map(w=><WallDrawing key={w.id} w={w} openings={p.openings.filter(o=>o.wallId===w.id)} selected={selection?.id===w.id} onDown={e=>downWall(e,w)} onOpening={onOpening}/>)}
 {labels&&rooms.filter(r=>!p.plannedSpaces?.some(z=>z.id===r.id)).map(s=><g key={s.id} onPointerDown={e=>{if(tool==='select'&&!placing){e.stopPropagation();onRoom(s)}}} style={{pointerEvents:'none'}}><text x={s.label.x} y={s.label.y} textAnchor="middle" fontSize={fs*.9} fill="#405e50" style={{paintOrder:'stroke',stroke:s.color,strokeWidth:.1,strokeLinejoin:'round'}}>{s.name.length>22?s.name.slice(0,20)+'…':s.name}</text><text x={s.label.x} y={s.label.y+fs*1.25} textAnchor="middle" fontSize={fs*.88} fill="#6e8176" style={{paintOrder:'stroke',stroke:s.color,strokeWidth:.1}}>{s.area.toFixed(1).replace('.',',')} м²</text></g>)}
 {(p.plannedSpaces||[]).filter(z=>z.level===level&&(labels||selection?.id===z.id)).map(z=><g key={z.id} onPointerDown={e=>downSpace(e,z)} style={{cursor:'move'}}><rect x={z.x+.08} y={z.y+.08} width={Math.min(z.w-.16,Math.max(1.5,z.name.length*fs*.48))} height={fs*2.9} rx={.05} fill={z.color} opacity={.95}/><text x={z.x+.16} y={z.y+.14+fs} fontSize={fs*.88} fill="#345447">{z.name.length>24?z.name.slice(0,22)+'…':z.name}</text><text x={z.x+.16} y={z.y+.14+fs*2.2} fontSize={fs*.8} fill="#597666">{(z.w*z.d).toFixed(1).replace('.',',')} м² · {z.enclosed?'комната':'зона'}</text></g>)}
 {selectedSpace&&<g data-editor="true"><rect x={selectedSpace.x} y={selectedSpace.y} width={selectedSpace.w} height={selectedSpace.d} stroke={ACC} fill="none" strokeWidth={.055} pointerEvents="none"/>{(['nw','ne','sw','se'] as const).map(c=><rect key={c} aria-label={'Размер пространства: '+c} x={selectedSpace.x+(c.includes('w')?0:selectedSpace.w)-handle} y={selectedSpace.y+(c.includes('n')?0:selectedSpace.d)-handle} width={handle*2} height={handle*2} fill="#fff" stroke={ACC} strokeWidth={.04} onPointerDown={e=>capture(e,{type:'space-resize',id:selectedSpace.id,corner:c})} style={{cursor:'nwse-resize'}}/>)}</g>}
 {placingPurpose&&ghostSize&&<g ref={spaceGhost} style={{display:'none'}} pointerEvents="none"><rect width={ghostSize.w} height={ghostSize.d} fill="#528d7528" stroke={ACC} strokeWidth={.08} strokeDasharray=".2 .1"/><text x={ghostSize.w/2} y={ghostSize.d/2} fontSize={fs} textAnchor="middle" fill={ACC}>{placingPurpose.name}</text></g>}
 {dimensions&&<><Dim a={{x:level?p.mezzanine.start:0,y:0}} b={{x:p.width,y:0}} text={mm(p.width-(level?p.mezzanine.start:0))} offset={-1.1} size={fs}/><Dim a={{x:level?p.mezzanine.start:0,y:0}} b={{x:level?p.mezzanine.start:0,y:p.depth}} text={mm(p.depth)} offset={-1.1} size={fs}/></>}
 {!level&&<g pointerEvents="none"><line x1={0} y1={p.depth+1.5} x2={p.width} y2={p.depth+1.5} stroke="#c3cec3" strokeWidth={.03} strokeDasharray=".3 .2"/><text x={p.width/2} y={p.depth+2.3} textAnchor="middle" fontSize={fs} fill="#7d8d80">ДОРОГА · ВХОД В ОФИС</text></g>}
 {selection?.type==='building'&&<g data-editor="true">{[{x:p.width,y:p.depth/2,edge:'right'},{x:p.width/2,y:p.depth,edge:'bottom'},{x:0,y:p.depth/2,edge:'left'}].map(pt=><circle key={pt.edge} cx={pt.x} cy={pt.y} r={handle*1.3} fill="#fff" stroke={ACC} strokeWidth={.05} onPointerDown={e=>capture(e,{type:'shell',edge:pt.edge})} style={{cursor:pt.edge==='bottom'?'ns-resize':'ew-resize'}}/>)}</g>}
 {selectedItem&&<g data-editor="true" transform={`translate(${selectedItem.x} ${selectedItem.y}) rotate(${selectedItem.rotation})`}><rect x={-selectedItem.w/2-.06} y={-selectedItem.d/2-.06} width={selectedItem.w+.12} height={selectedItem.d+.12} fill="none" stroke={ACC} strokeWidth={.04} pointerEvents="none"/>{!selectedItem.locked&&<>{(['nw','ne','sw','se'] as const).map(c=><rect key={c} x={(c.includes('w')?-1:1)*(selectedItem.w/2+handle)-handle} y={(c.includes('n')?-1:1)*(selectedItem.d/2+handle)-handle} width={handle*2} height={handle*2} fill="white" stroke={ACC} strokeWidth={.035} onPointerDown={e=>capture(e,{type:'resize',id:selectedItem.id,corner:c})} style={{cursor:'nwse-resize'}}/>)}<line x1={0} x2={0} y1={-selectedItem.d/2} y2={-selectedItem.d/2-handle*6} stroke={ACC} strokeWidth={.02}/><circle cx={0} cy={-selectedItem.d/2-handle*6} r={handle*1.3} fill="white" stroke={ACC} strokeWidth={.035} onPointerDown={e=>capture(e,{type:'rotate',id:selectedItem.id})} style={{cursor:'grab'}}/></>}<Dim a={{x:-selectedItem.w/2,y:selectedItem.d/2}} b={{x:selectedItem.w/2,y:selectedItem.d/2}} text={mm(selectedItem.w)} size={fs} offset={handle*4}/><Dim a={{x:selectedItem.w/2,y:-selectedItem.d/2}} b={{x:selectedItem.w/2,y:selectedItem.d/2}} text={mm(selectedItem.d)} size={fs} offset={handle*4}/></g>}
 {selectedWall&&<g data-editor="true">{(['a','b'] as const).map(end=><circle key={end} cx={selectedWall[end].x} cy={selectedWall[end].y} r={handle*1.3} fill="white" stroke={ACC} strokeWidth={.035} onPointerDown={e=>capture(e,{type:'wall-end',id:selectedWall.id,end})}/>)}<Dim a={selectedWall.a} b={selectedWall.b} text={mm(wallLength(selectedWall))} size={fs}/></g>}
 {(draft||measure)&&(()=>{const m=draft||measure!;return <g pointerEvents="none">{draft&&tool==='room'?<rect x={Math.min(m.a.x,m.b.x)} y={Math.min(m.a.y,m.b.y)} width={Math.abs(m.a.x-m.b.x)} height={Math.abs(m.a.y-m.b.y)} stroke={ACC} fill="#1b897411" strokeWidth={.07} strokeDasharray=".2 .1"/>:<line x1={m.a.x} y1={m.a.y} x2={m.b.x} y2={m.b.y} stroke={ACC} strokeWidth={.07} strokeDasharray=".2 .1"/>}<text x={(m.a.x+m.b.x)/2} y={(m.a.y+m.b.y)/2-.4} fontSize={fs*1.15} fill={ACC} textAnchor="middle">{tool==='room'?`${mm(Math.abs(m.a.x-m.b.x))} × ${mm(Math.abs(m.a.y-m.b.y))}`:mm(Math.hypot(m.a.x-m.b.x,m.a.y-m.b.y))} мм</text></g>})()}
 </svg>;
});
