'use client';
import {useRef,useState,useEffect,useImperativeHandle,forwardRef} from 'react';
import {Project,Point,Wall,Furniture,Opening,shell,mm,clone,round,uid,wallLength} from './model';
import {Space,moveWall,resizeBuilding,openingPosition} from './geometry';
import Symbol from './Symbol';
export type Selection={type:'item'|'wall'|'opening'|'room'|'building';id:string}|null;
export type Tool='select'|'wall'|'glass'|'room'|'door'|'window'|'opening'|'pan'|'measure';
export type CanvasAPI={fit:()=>void;zoom:(factor:number)=>void};
export type CanvasProps={project:Project;level:number;rooms:Space[];selection:Selection;tool:Tool;snap:boolean;labels:boolean;dimensions:boolean;placing:string|null;onSelect:(s:Selection)=>void;onUpdate:(p:Project)=>void;onBegin:()=>void;onAdd:(id:string,p:Point)=>void;onToolDone:()=>void;onRoom:(s:Space)=>void};
const ACC='#1b8974';
export function WallDrawing({w,openings,selected=false,onDown,onOpening}:{w:Wall;openings:Opening[];selected?:boolean;onDown?:(e:React.PointerEvent)=>void;onOpening?:(e:React.PointerEvent,o:Opening)=>void}){
 const l=wallLength(w),a=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x)*180/Math.PI;
 return <g><line x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke={selected?ACC:w.kind==='glass'?'#9ab9c2':'#34453f'} strokeWidth={w.thickness} strokeLinecap="square"/>{w.kind==='glass'&&<line x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke="#edf5f4" strokeWidth={w.thickness*.45}/>}<line data-wall={w.id} onPointerDown={onDown} x1={w.a.x} y1={w.a.y} x2={w.b.x} y2={w.b.y} stroke="transparent" strokeWidth={Math.max(.25,w.thickness+.1)} style={{cursor:'move'}}/>{openings.map(o=>{const width=Math.min(o.width,l),offset=Math.max(0,Math.min(o.offset,l-width));return <g key={o.id} data-opening={o.id} transform={`translate(${w.a.x} ${w.a.y}) rotate(${a}) translate(${offset} 0)`} onPointerDown={e=>onOpening?.(e,o)} style={{cursor:'ew-resize'}}><rect x={0} y={-w.thickness/2-.02} width={width} height={w.thickness+.04} fill="#f3f0e9"/>{o.kind==='door'?<g transform={o.flip?'scale(1 -1)':undefined}><path d={`M 0 0 L 0 ${-width}`} stroke="#69877f" strokeWidth={.025} fill="none"/><path d={`M ${width} 0 A ${width} ${width} 0 0 0 0 ${-width}`} stroke="#9baaa1" strokeWidth={.02} fill="none"/></g>:o.kind==='window'?<><line x1={0} y1={-.03} x2={width} y2={-.03} stroke="#5897ad" strokeWidth={.035}/><line x1={0} y1={.03} x2={width} y2={.03} stroke="#5897ad" strokeWidth={.035}/></>:null}<rect width={width} y={-.13} height={.26} fill="transparent"/></g>})}</g>
}
export function Dim({a,b,text,size=.3,offset=.5}:{a:Point;b:Point;text:string;size?:number;offset?:number}){const horizontal=Math.abs(a.y-b.y)<.01;return <g fill="#677c72" stroke="#8da097" strokeWidth={.017} pointerEvents="none">{horizontal?<><path d={`M ${a.x} ${a.y} V ${a.y+offset+.15} M ${b.x} ${b.y} V ${b.y+offset+.15} M ${a.x} ${a.y+offset} H ${b.x}`} fill="none"/>{[a.x,b.x].map(x=><path key={x} d={`M ${x-.1} ${a.y+offset+.1} l .2 -.2`}/>)}<text x={(a.x+b.x)/2} y={a.y+offset-.12} fontSize={size} stroke="none" textAnchor="middle">{text}</text></>:<><path d={`M ${a.x} ${a.y} H ${a.x+offset+.15} M ${b.x} ${b.y} H ${b.x+offset+.15} M ${a.x+offset} ${a.y} V ${b.y}`} fill="none"/><text transform={`translate(${a.x+offset-.12} ${(a.y+b.y)/2}) rotate(-90)`} fontSize={size} stroke="none" textAnchor="middle">{text}</text></>}</g>}
export const PlanCanvas=forwardRef<CanvasAPI,CanvasProps>(function PlanCanvas(props,ref){
 const {project:p,level,rooms,selection,tool,snap,labels,dimensions,placing,onSelect,onUpdate,onBegin,onAdd,onToolDone,onRoom}=props;
 const svg=useRef<SVGSVGElement>(null),drag=useRef<any>(null),[size,setSize]=useState({w:800,h:600}),[view,setView]=useState({x:-2,y:-7,w:44,h:26}),[draft,setDraft]=useState<{a:Point;b:Point}|null>(null),[measure,setMeasure]=useState<{a:Point;b:Point}|null>(null);const scale=size.w/view.w,fs=Math.max(.18,Math.min(.6,12/scale)),handle=Math.max(.07,4/scale);
 const fit=()=>{const w=p.width+5,h=Math.max(p.depth+6,w*size.h/size.w),ww=h*size.w/size.h;setView({x:(p.width-ww)/2,y:(p.depth-h)/2,w:ww,h});};
 useImperativeHandle(ref,()=>({fit,zoom:(factor)=>setView(v=>{const w=v.w/factor,h=v.h/factor;return {x:v.x+(v.w-w)/2,y:v.y+(v.h-h)/2,w,h}})}));
 useEffect(()=>{const el=svg.current;if(!el)return;const ob=new ResizeObserver(e=>{const r=e[0].contentRect;setSize({w:r.width||800,h:r.height||600})});ob.observe(el);return()=>ob.disconnect()},[]);
 useEffect(()=>{fit()},[size.w,size.h,level]);
 const point=(e:{clientX:number;clientY:number})=>{const m=svg.current?.getScreenCTM();if(!m)return {x:0,y:0};const q=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return {x:q.x,y:q.y}};
 const snapped=(q:Point,exact=false)=>{if(!snap||exact)return q;let x=round(q.x),y=round(q.y);for(const w of[...shell(p,level),...p.walls.filter(w=>w.level===level)])for(const a of[w.a,w.b]){if(Math.abs(a.x-x)<.12)x=a.x;if(Math.abs(a.y-y)<.12)y=a.y;}return {x,y}};
 useEffect(()=>{const el=svg.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const q=point(e),factor=Math.exp(Math.max(-.3,Math.min(.3,-e.deltaY*.0015)));setView(v=>{const w=Math.max(5,Math.min(180,v.w/factor)),f=w/v.w;return {x:q.x-(q.x-v.x)*f,y:q.y-(q.y-v.y)*f,w,h:v.h*f}})};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[view]);
 const capture=(e:React.PointerEvent,data:any)=>{e.stopPropagation();svg.current?.setPointerCapture(e.pointerId);drag.current={...data,start:point(e),baseline:clone(p),client:{x:e.clientX,y:e.clientY},view};if(data.type!=='pan'&&data.type!=='measure')onBegin();};
 const downItem=(e:React.PointerEvent,f:Furniture)=>{if(tool!=='select'||placing)return;onSelect({type:'item',id:f.id});if(f.locked){e.stopPropagation();return}capture(e,{type:'item',id:f.id});};
 const downWall=(e:React.PointerEvent,w:Wall)=>{if(['door','window','opening'].includes(tool)){e.stopPropagation();const q=point(e),l=wallLength(w),offset=((q.x-w.a.x)*(w.b.x-w.a.x)+(q.y-w.a.y)*(w.b.y-w.a.y))/l-.45;onBegin();const o:Opening={id:uid(),wallId:w.id,offset:Math.max(0,Math.min(l-.9,offset)),width:.9,height:tool==='window'?1.5:2.2,sill:tool==='window'?1:0,kind:tool as Opening['kind'],flip:false};onUpdate({...p,openings:[...p.openings,o]});onSelect({type:'opening',id:o.id});onToolDone();return}if(tool!=='select'||placing)return;if(w.id.startsWith('shell')){onSelect({type:'building',id:'building'});capture(e,{type:'shell',edge:w.id.split('-').pop()});return}onSelect({type:'wall',id:w.id});capture(e,{type:'wall',id:w.id});};
 const rootDown=(e:React.PointerEvent)=>{if(e.button===1||e.button===2||tool==='pan'){capture(e,{type:'pan'});return}const q=snapped(point(e),e.shiftKey);if(placing){onAdd(placing,q);return}if(['wall','glass','room','measure'].includes(tool)){capture(e,{type:tool,origin:q});setDraft({a:q,b:q});return}if(tool==='select')onSelect(null);};
 const move=(e:React.PointerEvent)=>{const d=drag.current;if(!d)return;const raw=point(e),q=snapped(raw,e.shiftKey),delta={x:raw.x-d.start.x,y:raw.y-d.start.y},b:Project=d.baseline;
 if(d.type==='pan'){const dx=(e.clientX-d.client.x)*d.view.w/size.w,dy=(e.clientY-d.client.y)*d.view.h/size.h;setView({...d.view,x:d.view.x-dx,y:d.view.y-dy});return}
 if(['wall','glass','room','measure'].includes(d.type)&&!d.id){let end=q;if(d.type==='wall'||d.type==='glass')end=Math.abs(q.x-d.origin.x)>Math.abs(q.y-d.origin.y)?{x:q.x,y:d.origin.y}:{x:d.origin.x,y:q.y};setDraft({a:d.origin,b:end});return}
 if(d.type==='item'){const f=b.furniture.find(f=>f.id===d.id)!;const x=snap?round(f.x+delta.x,e.shiftKey?.01:.05):f.x+delta.x,y=snap?round(f.y+delta.y,e.shiftKey?.01:.05):f.y+delta.y;onUpdate({...b,furniture:b.furniture.map(v=>v.id===f.id||f.group&&v.group===f.group?{...v,x:v.x+x-f.x,y:v.y+y-f.y}:v)});}
 if(d.type==='resize'){const f=b.furniture.find(f=>f.id===d.id)!,angle=f.rotation*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),dx=delta.x*c+delta.y*s,dy=-delta.x*s+delta.y*c,sx=d.corner.includes('w')?-1:1,sy=d.corner.includes('n')?-1:1,w=Math.min(20,Math.max(.1,round(f.w+sx*dx,snap?.05:.001))),dep=Math.min(20,Math.max(.1,round(f.d+sy*dy,snap?.05:.001))),cx=sx*(w-f.w)/2,cy=sy*(dep-f.d)/2;onUpdate({...b,furniture:b.furniture.map(v=>v.id===f.id?{...v,w,d:dep,x:round(f.x+cx*c-cy*s,.001),y:round(f.y+cx*s+cy*c,.001)}:v)});}
 if(d.type==='rotate'){const f=b.furniture.find(f=>f.id===d.id)!,a=Math.atan2(raw.y-f.y,raw.x-f.x)*180/Math.PI+90;onUpdate({...b,furniture:b.furniture.map(v=>v.id===f.id?{...v,rotation:round(a,e.shiftKey?1:15)}:v)});}
 if(d.type==='wall'){const w=b.walls.find(w=>w.id===d.id)!;onUpdate(moveWall(b,w.id,round(Math.abs(w.a.x-w.b.x)<.01?delta.x:delta.y,snap?.05:.001)));}
 if(d.type==='wall-end'){const w=b.walls.find(w=>w.id===d.id)!,vertical=Math.abs(w.a.x-w.b.x)<.01,next=vertical?{x:w.a.x,y:q.y}:{x:q.x,y:w.a.y},other=d.end==='a'?w.b:w.a;if(Math.hypot(next.x-other.x,next.y-other.y)>=.3)onUpdate({...b,walls:b.walls.map(v=>v.id===w.id?{...v,[d.end]:next}:v)});}
 if(d.type==='opening'){const o=b.openings.find(o=>o.id===d.id)!,w=[...shell(b,level),...b.walls].find(w=>w.id===o.wallId)!,l=wallLength(w),offset=((raw.x-w.a.x)*(w.b.x-w.a.x)+(raw.y-w.a.y)*(w.b.y-w.a.y))/l-o.width/2;onUpdate({...b,openings:b.openings.map(v=>v.id===o.id?{...v,offset:Math.max(0,Math.min(l-v.width,round(offset,snap?.05:.001)))}:v)});}
 if(d.type==='shell'){let w=b.width,h=b.depth;if(d.edge==='right')w=round(b.width+delta.x,.1);if(d.edge==='left')w=round(b.width-delta.x,.1);if(d.edge==='bottom')h=round(b.depth+delta.y,.1);if(d.edge==='top')h=round(b.depth-delta.y,.1);onUpdate(resizeBuilding(b,Math.min(100,Math.max(5,w)),Math.min(100,Math.max(5,h))));}
 };
 const end=()=>{const d=drag.current;if(!d)return;if(draft&&['wall','glass','room','measure'].includes(d.type)&&!d.id){const {a,b}=draft,len=Math.hypot(a.x-b.x,a.y-b.y);if(d.type==='measure'){setMeasure(draft)}else if(len>.4){const next=clone(p);if(d.type==='room'){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y);if(w>=1&&h>=1){const pts=[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}];const walls=pts.map((a,i)=>({id:uid(),a,b:pts[(i+1)%4],kind:'wall' as const,thickness:.15,height:3.1,level}));next.walls.push(...walls);next.openings.push({id:uid(),wallId:walls[2].id,offset:.3,width:.9,height:2.2,sill:0,kind:'door',flip:false});next.tags.push({id:uid(),x:x+w/2,y:y+h/2,name:'Новое помещение',color:'#e5ebe3',level,notes:''});}}else next.walls.push({id:uid(),a,b,kind:d.type==='glass'?'glass':'wall',height:3.1,thickness:d.type==='glass'?.1:.15,level});onUpdate(next);onToolDone();}}
 drag.current=null;setDraft(null);};
 const selectedItem=selection?.type==='item'?p.furniture.find(f=>f.id===selection.id):null,selectedWall=selection?.type==='wall'?p.walls.find(w=>w.id===selection.id):null;
 const onOpening=(e:React.PointerEvent,o:Opening)=>{if(tool!=='select'||placing)return;onSelect({type:'opening',id:o.id});capture(e,{type:'opening',id:o.id})};
 return <svg ref={svg} className={`plan-svg tool-${tool}`} viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`} onPointerDown={rootDown} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onContextMenu={e=>e.preventDefault()} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/x-office-item');if(id)onAdd(id,snapped(point(e)))}} aria-label="План офиса: перетаскивайте предметы и стены">
 <defs><pattern id="plan-grid" width={1} height={1} patternUnits="userSpaceOnUse"><path d="M 1 0 H 0 V 1" fill="none" stroke="#a8b7ae" strokeOpacity={.3} strokeWidth={.01}/></pattern></defs>
 {level===1&&<g><rect width={p.mezzanine.start} height={p.depth} fill="#e4e8e1" opacity={.35}/><text x={p.mezzanine.start/2} y={p.depth/2} textAnchor="middle" fontSize={fs*1.3} fill="#87958c">Второй свет · перекрытия нет</text></g>}
 <rect x={level?p.mezzanine.start:0} width={level?p.width-p.mezzanine.start:p.width} height={p.depth} fill="#edece4"/>
 {rooms.map(s=><g key={s.id} onPointerDown={e=>{if(tool==='select'&&!placing){e.stopPropagation();onRoom(s)}}}>{s.rects.map((r,i)=><rect key={i} x={r.x} y={r.y} width={r.w+.0005} height={r.h+.0005} fill={s.color} stroke={selection?.id===s.id?ACC:undefined} strokeWidth={.008}/>)}</g>)}
 {snap&&<rect x={level?p.mezzanine.start:0} width={level?p.width-p.mezzanine.start:p.width} height={p.depth} fill="url(#plan-grid)" pointerEvents="none"/>}
 {p.furniture.filter(f=>f.level===level).sort((a,b)=>(a.kind==='rug'?-1:0)-(b.kind==='rug'?-1:0)).map(f=><g key={f.id} data-item={f.id} transform={`translate(${f.x} ${f.y}) rotate(${f.rotation})`} onPointerDown={e=>downItem(e,f)} style={{cursor:f.locked?'not-allowed':'move'}}><Symbol item={f}/><rect x={-f.w/2} y={-f.d/2} width={f.w} height={f.d} fill="transparent"/></g>)}
 {[...p.walls.filter(w=>w.level===level),...shell(p,level)].map(w=><WallDrawing key={w.id} w={w} openings={p.openings.filter(o=>o.wallId===w.id)} selected={selection?.id===w.id} onDown={e=>downWall(e,w)} onOpening={onOpening}/>)}
 {labels&&rooms.map(s=><g key={s.id} onPointerDown={e=>{if(tool==='select'&&!placing){e.stopPropagation();onRoom(s)}}} style={{cursor:'pointer'}}><text x={s.label.x} y={s.label.y} textAnchor="middle" fontSize={fs*.9} fill="#405e50" style={{paintOrder:'stroke',stroke:s.color,strokeWidth:.1,strokeLinejoin:'round'}}>{s.name.length>22?s.name.slice(0,20)+'…':s.name}</text><text x={s.label.x} y={s.label.y+fs*1.25} textAnchor="middle" fontSize={fs*.88} fill="#6e8176" style={{paintOrder:'stroke',stroke:s.color,strokeWidth:.1}}>{s.area.toFixed(1).replace('.',',')} м²</text></g>)}
 {dimensions&&<><Dim a={{x:0,y:0}} b={{x:p.width,y:0}} text={mm(p.width)} offset={-1.1} size={fs}/><Dim a={{x:0,y:0}} b={{x:0,y:p.depth}} text={mm(p.depth)} offset={-1.1} size={fs}/></>}
 {!level&&<g pointerEvents="none"><line x1={0} y1={p.depth+1.5} x2={p.width} y2={p.depth+1.5} stroke="#c3cec3" strokeWidth={.03} strokeDasharray=".3 .2"/><text x={p.width/2} y={p.depth+2.3} textAnchor="middle" fontSize={fs} fill="#7d8d80">ДОРОГА · ВХОД В ОФИС</text></g>}
 {selection?.type==='building'&&<g data-editor="true">{[{x:p.width,y:p.depth/2,edge:'right'},{x:p.width/2,y:p.depth,edge:'bottom'},{x:0,y:p.depth/2,edge:'left'}].map(pt=><circle key={pt.edge} cx={pt.x} cy={pt.y} r={handle*1.3} fill="#fff" stroke={ACC} strokeWidth={.05} onPointerDown={e=>capture(e,{type:'shell',edge:pt.edge})} style={{cursor:pt.edge==='bottom'?'ns-resize':'ew-resize'}}/>)}</g>}
 {selectedItem&&<g data-editor="true" transform={`translate(${selectedItem.x} ${selectedItem.y}) rotate(${selectedItem.rotation})`}><rect x={-selectedItem.w/2-.06} y={-selectedItem.d/2-.06} width={selectedItem.w+.12} height={selectedItem.d+.12} fill="none" stroke={ACC} strokeWidth={.04} pointerEvents="none"/>{!selectedItem.locked&&<>{(['nw','ne','sw','se'] as const).map(c=><rect key={c} x={(c.includes('w')?-1:1)*(selectedItem.w/2+handle)-handle} y={(c.includes('n')?-1:1)*(selectedItem.d/2+handle)-handle} width={handle*2} height={handle*2} fill="white" stroke={ACC} strokeWidth={.035} onPointerDown={e=>capture(e,{type:'resize',id:selectedItem.id,corner:c})} style={{cursor:'nwse-resize'}}/>)}<line x1={0} x2={0} y1={-selectedItem.d/2} y2={-selectedItem.d/2-handle*6} stroke={ACC} strokeWidth={.02}/><circle cx={0} cy={-selectedItem.d/2-handle*6} r={handle*1.3} fill="white" stroke={ACC} strokeWidth={.035} onPointerDown={e=>capture(e,{type:'rotate',id:selectedItem.id})} style={{cursor:'grab'}}/></>}<Dim a={{x:-selectedItem.w/2,y:selectedItem.d/2}} b={{x:selectedItem.w/2,y:selectedItem.d/2}} text={mm(selectedItem.w)} size={fs} offset={handle*4}/><Dim a={{x:selectedItem.w/2,y:-selectedItem.d/2}} b={{x:selectedItem.w/2,y:selectedItem.d/2}} text={mm(selectedItem.d)} size={fs} offset={handle*4}/></g>}
 {selectedWall&&<g data-editor="true">{(['a','b'] as const).map(end=><circle key={end} cx={selectedWall[end].x} cy={selectedWall[end].y} r={handle*1.3} fill="white" stroke={ACC} strokeWidth={.035} onPointerDown={e=>capture(e,{type:'wall-end',id:selectedWall.id,end})}/>)}<Dim a={selectedWall.a} b={selectedWall.b} text={mm(wallLength(selectedWall))} size={fs}/></g>}
 {(draft||measure)&&(()=>{const m=draft||measure!;return <g pointerEvents="none">{draft&&tool==='room'?<rect x={Math.min(m.a.x,m.b.x)} y={Math.min(m.a.y,m.b.y)} width={Math.abs(m.a.x-m.b.x)} height={Math.abs(m.a.y-m.b.y)} stroke={ACC} fill="#1b897411" strokeWidth={.07} strokeDasharray=".2 .1"/>:<line x1={m.a.x} y1={m.a.y} x2={m.b.x} y2={m.b.y} stroke={ACC} strokeWidth={.07} strokeDasharray=".2 .1"/>}<text x={(m.a.x+m.b.x)/2} y={(m.a.y+m.b.y)/2-.4} fontSize={fs*1.15} fill={ACC} textAnchor="middle">{tool==='room'?`${mm(Math.abs(m.a.x-m.b.x))} × ${mm(Math.abs(m.a.y-m.b.y))}`:mm(Math.hypot(m.a.x-m.b.x,m.a.y-m.b.y))} мм</text></g>})()}
 </svg>;
});
