'use client';
import {useMemo,useState} from 'react';
import {ArrowRight,Check,Info,LayoutGrid,Route,Save} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {SPACE_GROUPS,SPACE_PURPOSES,CUSTOMER_ROUTE,createProgramme,programmeTotals,programmeChecks,programmeFor,buildingCapacity,placedProgramme,spaceMode,purpose} from './salesOffice';
import type {OfficeFormat,OfficeProgramme} from './programmeTypes';
import type {Project} from './model';
const a=(n:number)=>n.toLocaleString('ru-RU',{maximumFractionDigits:1});
function AreaInput({value,onCommit,label}:{value:number;onCommit:(n:number)=>void;label:string}){const [draft,setDraft]=useState(String(value));return <input key={value} aria-label={label} type="number" min={1} max={150} step={.5} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{const n=Number(draft);if(Number.isFinite(n)&&n>=1&&n<=150)onCommit(n);else setDraft(String(value))}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/>}
export default function ProgrammeDialog({project,onClose,onSave,onBlank}:{project:Project;onClose:()=>void;onSave:(p:OfficeProgramme)=>void;onBlank:(p:OfficeProgramme)=>void}){
 const [draft,setDraft]=useState(()=>structuredClone(programmeFor(project))),[tab,setTab]=useState('composition'),[group,setGroup]=useState('public');const totals=programmeTotals(draft),capacity=buildingCapacity(project),placed=useMemo(()=>placedProgramme(project),[project]);
 const patch=(id:string,change:{quantity?:number;unitArea?:number})=>setDraft(p=>({...p,items:p.items.map(r=>r.purposeId===id?{...r,...change}:r)}));
 const changeFormat=(format:OfficeFormat)=>{setDraft(createProgramme(format));setGroup('public')};
 const selected=draft.items.filter(r=>purpose(r.purposeId)?.group===group),missing=draft.items.filter(r=>r.quantity>placed.filter(z=>z.purposeId===r.purposeId).length);
 return <Dialog open onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="programme-dialog"><DialogHeader><span className="panel-eyebrow">ПОМОЩНИК ПО ПРОСТРАНСТВУ</span><DialogTitle>Состав офиса продаж</DialogTitle><DialogDescription>Выберите основу, уточните количество помещений и собирайте план готовыми пространствами.</DialogDescription></DialogHeader>
 <div className="office-formats">{([{n:200,title:'Компактный',desc:'3 кабинета · функции совмещены'},{n:400,title:'Полноценный',desc:'4 кабинета · отдельные службы'},{n:600,title:'Расширенный',desc:'5 кабинетов + VIP · 2 банка'}] as const).map(f=><button key={f.n} onClick={()=>changeFormat(f.n)} aria-pressed={draft.format===f.n}><span>{f.n} м² {draft.format===f.n&&<Check size={17}/>}</span><b>{f.title}</b><small>{f.desc}</small></button>)}</div>
 <nav className="programme-tabs" aria-label="Разделы состава"><button aria-pressed={tab==='composition'} onClick={()=>setTab('composition')}><LayoutGrid size={16}/>Помещения и площади</button><button aria-pressed={tab==='logic'} onClick={()=>setTab('logic')}><Route size={16}/>Как связать зоны</button><button aria-pressed={tab==='progress'} onClick={()=>setTab('progress')}>На плане · {placed.length}</button></nav>
 <div className="programme-body"><section className="programme-content">
 {tab==='composition'&&<><div className="programme-groups">{SPACE_GROUPS.map(g=><button key={g.id} aria-pressed={group===g.id} onClick={()=>setGroup(g.id)}><i style={{background:g.color}}/>{g.name}<small>{a(totals.groups.find(s=>s.id===g.id)!.area)} м²</small></button>)}</div><div className="programme-rows"><div className="programme-row-heading"><span>Пространство</span><span>Кол-во</span><span>м² / шт.</span><span>Всего</span></div>{selected.map(r=>{const d=purpose(r.purposeId)!;return <div className={'programme-row'+(!r.quantity?' inactive':'')} key={r.purposeId}><div><b>{d.name}</b><small>{r.quantity?{room:'Отдельная комната',zone:'Открытая зона',niche:'Шкаф / ниша'}[spaceMode(d.id,draft.format)]:d.combined||'Не включено в этот формат'}</small><details><summary>Логика размещения</summary><p>{d.note}</p></details></div><div className="quantity-stepper"><button aria-label={'Уменьшить: '+d.name} disabled={!r.quantity} onClick={()=>patch(d.id,{quantity:r.quantity-1})}>−</button><output aria-label={'Количество: '+d.name}>{r.quantity}</output><button aria-label={'Добавить: '+d.name} disabled={r.quantity>=20} onClick={()=>patch(d.id,{quantity:r.quantity+1})}>+</button></div><AreaInput key={r.purposeId+':'+r.unitArea} label={'Площадь: '+d.name} value={r.unitArea} onCommit={unitArea=>patch(d.id,{unitArea})}/><b className="area-subtotal">{a(r.quantity*r.unitArea)}</b></div>})}</div><p className="programme-footnote">Площади из вашего задания — отправные ориентиры, не нормативные минимумы. В площади каждой зоны уже учитываются проходы между её мебелью.</p></>}
 {tab==='logic'&&<div className="office-logic"><h3>Маршрут покупателя</h3><ol className="customer-route">{CUSTOMER_ROUTE.map((s,i)=><li key={s}><span>{i+1}</span>{s}{i<CUSTOMER_ROUTE.length-1&&<ArrowRight size={14}/>}</li>)}</ol><div className="logic-pairs"><article><h3>Один общий клиентский зал</h3><p>Ресепшен, ожидание, макет, кофе и детская — зоны единого пространства. Стены здесь не добавляются автоматически.</p></article><article><h3>Кабинет менеджера = встреча с клиентом</h3><p>К пяти кабинетам продаж не добавляются ещё пять переговорных. VIP может принять шестого покупателя при пиковом потоке.</p></article><article><h3>Команда за границей клиентской части</h3><p>Маркетинг, колл-центр, сопровождение и архив можно вынести на второй ярус. Посетителям оставьте понятный маршрут на первом этаже.</p></article><article><h3>Детская рядом с ожиданием</h3><p>Родители видят детей; вход, горячие напитки и основной проход остаются в стороне.</p></article><article><h3>Хозяйственные функции разделены</h3><p>Моповая отдельно от кухни, продуктовых запасов и архива. Гостевые и служебные санузлы — разные блоки.</p></article><article><h3>Банк — консультации</h3><p>Кассовый пункт и хранение наличных не включены. Колл-центр отделяется по звуку от клиентских переговоров.</p></article></div><p className="programme-footnote">Связи — подсказки для ручной планировки. Проходимость маршрута, акустика, санитарное разделение и доступность автоматически не подтверждаются.</p></div>}
 {tab==='progress'&&<div className="programme-progress"><h3>План и выбранный состав</h3><p>Учитываются готовые пространства и комнаты, которым вы назначили функцию. Их площади не прибавляются к экспликации повторно.</p>{draft.items.filter(r=>r.quantity).map(r=>{const found=placed.filter(z=>z.purposeId===r.purposeId),actual=found.reduce((s,z)=>s+z.area,0);return <div key={r.purposeId}><span>{purpose(r.purposeId)?.name}</span><b>{found.length} / {r.quantity}</b><small>{a(actual)} / {a(r.quantity*r.unitArea)} м²</small></div>})}<p>{missing.length?'Ещё нужно разместить или назначить функции существующим комнатам.':'Все функции состава отмечены на плане. Геометрию и проходы проверьте отдельно.'}</p></div>}
 </section><aside className="programme-balance"><h3>Баланс площадей</h3><div className="balance-total"><b>{a(totals.gross)}</b><span>м² нужно по составу</span></div><div className="area-stack" aria-hidden="true">{totals.groups.map(g=><i key={g.id} style={{background:g.color,flex:g.area}}/>)}<i style={{background:'#f1f2ee',flex:totals.reserve}}/></div>{totals.groups.map(g=><div className="balance-line" key={g.id}><span><i style={{background:g.color}}/>{g.name}</span><b>{a(g.area)}</b></div>)}<div className="balance-line strong"><span>Сумма зон</span><b>{a(totals.net)} м²</b></div><label className="reserve-field">Резерв общих проходов и стен<select aria-label="Резерв площади" value={draft.reservePercent} onChange={e=>setDraft(p=>({...p,reservePercent:Number(e.target.value)}))}>{[10,15,20,25,30,35,40].map(n=><option key={n} value={n}>{n}%</option>)}</select></label><div className="balance-line"><span>Резерв</span><b>{a(totals.reserve)} м²</b></div><p className="area-formula">{a(totals.net)} ÷ {a(1-draft.reservePercent/100)} = {a(totals.gross)} м²</p><div className={'capacity-note'+(totals.gross>capacity+.1?' over':'')}><b>Контур этажей: {a(capacity)} м²</b><span>{totals.gross>capacity+.1?`Состав превышает его на ${a(totals.gross-capacity)} м²`:`Запас по контуру: ${a(capacity-totals.gross)} м²`}</span><small>До вычета наружных стен и лестничного проёма. Совпадение площадей ещё не означает, что расстановка поместится.</small></div>{programmeChecks(draft).map(msg=><p className="programme-advice" key={msg}><Info size={15}/>{msg}</p>)}</aside></div>
 <footer className="programme-footer"><p>Состав сохраняется с проектом. Расстановка выбирается отдельно.</p><button className="secondary" onClick={()=>onBlank(draft)}>Пустой вариант в этом контуре</button><button className="primary" onClick={()=>onSave(draft)}><Save size={16}/>Сохранить состав</button></footer>
 </DialogContent></Dialog>;
}
