'use client';
import {useState} from 'react';
import {ArrowRight,Plus,Search,Square,DoorOpen,LayoutGrid,Check} from 'lucide-react';
import type {Project} from './model';
import type {LibraryDrop,ClientPoint} from './useLibraryDrag';
import {useLibraryDrag} from './useLibraryDrag';
import {SPACE_GROUPS,SPACE_PURPOSES,programmeFor,placedProgramme,spaceMode,purpose} from './salesOffice';
import {moduleDimensions,moduleFurniture} from './spaceModules';
import Symbol from './Symbol';
export function SpacePreview({id,area,project}:{id:string;area:number;project:Project}){let size;try{size=moduleDimensions(id,area)}catch{return <div className="space-preview-invalid">Увеличьте площадь в составе</div>};const {w,d}=size,enclosed=spaceMode(id,programmeFor(project).format)==='room',items=moduleFurniture({id:'preview',purposeId:id,name:'',x:0,y:0,w,d,color:'#eef2e9',enclosed,level:0});return <svg className="space-preview" viewBox={`-.3 -.3 ${w+.6} ${d+.6}`} aria-hidden="true"><rect width={w} height={d} fill={SPACE_GROUPS.find(g=>g.id===purpose(id)?.group)?.color} stroke={enclosed?'#5b6c60':'#b4c4b5'} strokeWidth={enclosed?.11:.04} strokeDasharray={enclosed?undefined:'.15 .12'}/>{items.map(f=><g key={f.id} transform={`translate(${f.x} ${f.y}) rotate(${f.rotation})`}><Symbol item={f} detail={false}/></g>)}{enclosed&&<path d={`M .3 ${d} h .9 m -.9 0 v -.9 a .9 .9 0 0 1 .9 .9`} fill="none" stroke="#f7f8f3" strokeWidth={.13}/>}</svg>}
export default function SpaceLibrary({project,level,placing,onPlace,onDrop,onDrag,onProgramme,onDraw}:{project:Project;level:number;placing:string|null;onPlace:(id:string)=>void;onDrop:(p:LibraryDrop,q:ClientPoint)=>void;onDrag:()=>void;onProgramme:()=>void;onDraw:()=>void}){
 const [group,setGroup]=useState('all'),[search,setSearch]=useState(''),[all,setAll]=useState(false),[details,setDetails]=useState<string|null>(null),p=programmeFor(project),placed=placedProgramme(project),drag=useLibraryDrag(onDrag,onDrop);
 const entries=SPACE_PURPOSES.filter(d=>(group==='all'||d.group===group)&&d.name.toLowerCase().includes(search.toLowerCase())&&(all||(p.items.find(r=>r.purposeId===d.id)?.quantity||0)>0));const selected=details?purpose(details):null;
 return <aside className="catalog-panel space-library"><span className="library-eyebrow">ГОТОВЫЕ РЕШЕНИЯ</span><h2>Пространства</h2><button className="space-programme-launch" onClick={onProgramme}><LayoutGrid size={21}/><span><b>Состав офиса · {p.format} м²</b><small>{project.programme?'Изменить состав и проверить площади':'Выбрать помещения и площади'}</small></span><ArrowRight size={16}/></button><div className="search-field"><Search size={16}/><input aria-label="Поиск пространств" placeholder="Кабинет, ожидание, кухня…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="space-group-select" aria-label="Группа пространств" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Все группы</option>{SPACE_GROUPS.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><label className="show-all-spaces"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Показывать функции вне состава</label><p className="space-instruction">Перетащите пространство на свободное место. Комнаты получат стены и дверь, открытые зоны — только зонирование и мебель.</p>{level===1&&<p className="upper-note">На втором ярусе удобно разместить команду и служебные помещения.</p>}
 <div className="space-cards">{entries.map(d=>{const row=p.items.find(r=>r.purposeId===d.id),area=row?.unitArea||12,count=placed.filter(z=>z.purposeId===d.id).length,mode=spaceMode(d.id,p.format);return <article key={d.id} className={'space-card'+(placing==='space:'+d.id?' selected':'')}><button className="space-card-place" {...drag.handlers({itemId:'space:'+d.id},d.name)} onClick={()=>drag.activate(()=>onPlace('space:'+d.id))} aria-label={'Добавить пространство: '+d.name}><SpacePreview id={d.id} area={area} project={project}/><div><strong>{d.name}</strong><span>{area} м² · {mode==='room'?'со стенами':mode==='niche'?'шкаф / ниша':'открытая зона'}</span><small>{count?`${count} на плане`:''}{row?.quantity?`${count?' · ':''}нужно ${row.quantity}`:''}</small></div><Plus size={16}/></button><button className="space-explain" onClick={()=>setDetails(details===d.id?null:d.id)} aria-expanded={details===d.id}>Как разместить <ArrowRight size={12}/></button>{details===d.id&&selected&&<div className="space-guidance"><p>{selected.note}</p>{selected.near.length>0&&<p><b>Рядом:</b> {selected.near.map(id=>purpose(id)?.name).join(', ')}.</p>}{selected.away.length>0&&<p><b>Отделить от:</b> {selected.away.map(id=>purpose(id)?.name).join(', ')}.</p>}{selected.upper&&<small>Можно рассмотреть размещение на втором ярусе.</small>}</div>}</article>})}</div>{!entries.length&&<p className="empty-message">Нет подходящих пространств. Измените поиск или группу.</p>}<button className="secondary full-width draw-space" onClick={onDraw}><Square size={16}/>Нарисовать комнату вручную</button><p className="catalog-note">В уже готовой комнате выберите её пол и назначьте функцию из состава. Это учтёт комнату без добавления новых стен.</p>{drag.ghost}</aside>;
}
