'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {Project,Furniture,Wall,shell,wallLength} from './model';
import {spaces} from './geometry';
import {Switch} from '@/components/ui/switch';
import {RotateCcw,Camera} from 'lucide-react';
export default function ThreeView({project:p,level,onSelect}:{project:Project;level:number;onSelect:(id:string)=>void}){
 const host=useRef<HTMLDivElement>(null),runtime=useRef<any>(null),[error,setError]=useState(''),[cut,setCut]=useState(true),[all,setAll]=useState(false);
 const reset=()=>{const r=runtime.current;if(r){const left=level&&!all?p.mezzanine.start:0,width=p.width-left,base=level&&!all?p.mezzanine.height:0,center=new THREE.Vector3(left+width/2,base+.7,p.depth/2),radius=Math.hypot(width,p.depth,p.height)/2,fov=r.camera.fov*Math.PI/180,angle=Math.min(fov,2*Math.atan(Math.tan(fov/2)*r.camera.aspect)),distance=radius/Math.sin(angle/2)*1.08;const direction=new THREE.Vector3(.23,.72,1).normalize();r.camera.position.copy(center).addScaledVector(direction,distance);r.controls.target.copy(center);r.controls.maxDistance=Math.max(180,distance*3);r.camera.far=Math.max(500,distance*5);r.camera.updateProjectionMatrix();r.controls.update()}};
 const resetRef=useRef(reset);resetRef.current=reset;
 useEffect(()=>{const el=host.current;if(!el)return;let r:THREE.WebGLRenderer;try{r=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true})}catch{setError('Браузер не смог включить 3D. План и все размеры доступны в режиме 2D.');return}
 r.setPixelRatio(Math.min(devicePixelRatio,2));r.shadowMap.enabled=true;r.shadowMap.type=THREE.PCFShadowMap;r.setClearColor('#eef1eb');r.outputColorSpace=THREE.SRGBColorSpace;el.appendChild(r.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,1,.1,500),controls=new OrbitControls(camera,r.domElement);controls.enableDamping=true;controls.dampingFactor=.1;controls.maxPolarAngle=Math.PI/2.06;controls.minDistance=3;controls.maxDistance=180;controls.screenSpacePanning=true;
 const ambient=new THREE.HemisphereLight('#ffffff','#b8c4b4',2.4);scene.add(ambient);const sun=new THREE.DirectionalLight('#fff8e9',3);sun.position.set(-10,35,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;sun.shadow.bias=-.0003;scene.add(sun);
 const group=new THREE.Group();scene.add(group);runtime.current={r,scene,camera,controls,group};reset();
 const resize=()=>{r.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();resetRef.current()};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0;const loop=()=>{controls.update();r.render(scene,camera);frame=requestAnimationFrame(loop)};loop();
 let start={x:0,y:0};const down=(e:PointerEvent)=>{start={x:e.clientX,y:e.clientY}},click=(e:PointerEvent)=>{if(Math.hypot(start.x-e.clientX,start.y-e.clientY)>5)return;const rect=r.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(group.children,true).find(h=>h.object.userData.itemId);if(hit)onSelect(hit.object.userData.itemId)};r.domElement.addEventListener('pointerdown',down);r.domElement.addEventListener('pointerup',click);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();scene.traverse((o:any)=>{o.geometry?.dispose();if(o.material){if(Array.isArray(o.material))o.material.forEach((m:any)=>m.dispose());else o.material.dispose()}});r.dispose();r.domElement.remove();runtime.current=null};
 },[]);
 useEffect(()=>{resetRef.current()},[level,all]);
 useEffect(()=>{const rt=runtime.current;if(!rt)return;const root:THREE.Group=rt.group;for(const child of[...root.children]){child.traverse((o:any)=>{o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach((m:any)=>m.dispose());else o.material?.dispose()});root.remove(child)}
 const box=(parent:THREE.Group,x:number,y:number,z:number,w:number,h:number,d:number,color:string,opacity=1)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.01,w),Math.max(.01,h),Math.max(.01,d)),new THREE.MeshStandardMaterial({color,roughness:.7,transparent:opacity<1,opacity,depthWrite:opacity>=1}));mesh.position.set(x,y,z);mesh.castShadow=opacity===1;mesh.receiveShadow=true;parent.add(mesh);return mesh};
 const cyl=(parent:THREE.Group,x:number,y:number,z:number,r:number,h:number,color:string)=>{const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,24),new THREE.MeshStandardMaterial({color,roughness:.75}));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m};
 const furniture=(f:Furniture,base:number)=>{const g=new THREE.Group();g.position.set(f.x,f.kind==='stair'?0:base,f.y);g.rotation.y=-f.rotation*Math.PI/180;const {w,d,h,color}=f;
 const b=(x:number,y:number,z:number,a:number,b:number,c:number,co=color)=>box(g,x,y,z,a,b,c,co);
 if(['desk','table','meeting','round'].includes(f.kind)){if(f.kind==='round')cyl(g,0,h-.04,0,w/2,.08,color);else b(0,h-.04,0,w,.08,d);for(const x of[-w*.37,w*.37])for(const z of[-d*.34,d*.34])b(x,h/2-.04,z,.055,h-.08,.055,'#5b6d65');if(f.kind==='desk'){b(0,h+.18,-d*.25,w*.3,.3,.04,'#536b70');b(0,h+.025,.08,w*.27,.035,.13,'#d9dfdf')}}
 else if(['sofa','armchair','chair'].includes(f.kind)){b(0,.4,0,w,.18,d);b(0,h*.65,-d*.4,w,h*.7,d*.17);if(f.kind!=='chair'){b(-w*.43,.55,0,w*.14,.35,d);b(w*.43,.55,0,w*.14,.35,d)}for(const x of[-w*.36,w*.36])for(const z of[-d*.3,d*.3])b(x,.17,z,.055,.34,.055,'#59685e');}
 else if(f.kind==='plant'){cyl(g,0,h*.17,0,w*.3,h*.34,'#d1d8ca');b(0,h*.5,0,.055,h*.65,.055,'#6a785b');for(let i=0;i<5;i++){const mesh=new THREE.Mesh(new THREE.SphereGeometry(w*.3,10,8),new THREE.MeshStandardMaterial({color}));mesh.scale.set(1,1.3,.8);mesh.position.set(Math.sin(i*2)*w*.2,h*.62+i*h*.06,Math.cos(i*2)*d*.2);g.add(mesh)}}
 else if(f.kind==='model'){b(0,h/2,0,w,h,d);b(0,h+.02,0,w*.91,.04,d*.87,'#b2c4b1');for(let i=0;i<4;i++)b(-w*.35+i*w*.22,h+.3,0,w*.14,.6,d*(i%2?.45:.65),'#f5f5ed')}
 else if(f.kind==='wc'){cyl(g,0,.35,.08,w*.44,.5,color);b(0,h*.6,-d*.35,w,h*.8,d*.25)}
 else if(f.kind==='sink'){b(0,h/2,0,w,h,d);b(0,h+.02,0,w*.7,.035,d*.65,'#abc8cd')}
 else if(f.kind==='stair'){for(let i=0;i<10;i++){b(-w*.25,(i+1)*h/40,d*.45-i*d*.07,w*.46,(i+1)*h/20,d*.07);b(w*.25,(20-i)*h/40,d*.45-i*d*.07,w*.46,(20-i)*h/20,d*.07)}b(0,h/2-.08,-d*.36,w,.16,d*.28)}
 else if(f.kind==='stool'){cyl(g,0,h-.06,0,w/2,.12,color);cyl(g,0,h/2,0,.035,h,'#5a6e62')}
 else b(0,h/2,0,w,h,d);
 g.traverse(o=>{o.userData.itemId=f.id});root.add(g);
 };
 const wall=(w:Wall,base:number)=>{const length=wallLength(w);if(length<.02)return;const height=cut?Math.min(1.2,w.height):w.height,angle=Math.atan2(w.b.y-w.a.y,w.b.x-w.a.x),g=new THREE.Group();g.position.set(w.a.x,base,w.a.y);g.rotation.y=-angle;root.add(g);const ops=p.openings.filter(o=>o.wallId===w.id).sort((a,b)=>a.offset-b.offset),parts=[];let cursor=0;const solid=(a:number,b:number,bottom=0,top=height)=>{if(b-a>.01&&top-bottom>.01)box(g,(a+b)/2,(bottom+top)/2,0,b-a,top-bottom,w.thickness,w.kind==='glass'?'#9cc9d7':'#e2e7de',w.kind==='glass'?.3:1)};for(const o of ops){const a=Math.max(cursor,Math.min(length,o.offset)),b=Math.min(length,a+o.width);solid(cursor,a);const sill=o.kind==='window'?o.sill:0;solid(a,b,0,Math.min(height,sill));solid(a,b,Math.min(height,sill+o.height),height);if(o.kind==='window')box(g,(a+b)/2,Math.min(height,sill+o.height/2),0,b-a,Math.max(.1,Math.min(height-sill,o.height)),.025,'#9ac9db',.25);cursor=b;}solid(cursor,length);};
 const levels=all&&p.mezzanine.enabled?[0,1]:[level];
 for(const l of levels){const base=l?p.mezzanine.height:0;const rs=spaces(p,l);for(const room of rs)for(const rect of room.rects)box(root,rect.x+rect.w/2,base-.07,rect.y+rect.h/2,rect.w,.14,rect.h,room.color);for(const w of[...shell(p,l),...p.walls.filter(w=>w.level===l)])wall(w,base);for(const f of p.furniture.filter(f=>f.level===l&&!(all&&l===1&&f.kind==='stair')))furniture(f,base)}
 if(!level||all){box(root,p.width/2,-.2,p.depth+2,p.width,.08,1.5,'#d2d9d0');const road=new THREE.GridHelper(p.width,Math.round(p.width),'#e2e7df','#e2e7df');road.position.set(p.width/2,-.3,p.depth/2);root.add(road)}
 },[p,level,cut,all]);
 return <div className="three-container"><div ref={host} className="three-host"/>{error&&<div className="three-error">{error}</div>}<div className="three-settings"><label><Switch checked={cut} onCheckedChange={setCut}/>Срез стен</label>{p.mezzanine.enabled&&<label><Switch checked={all} onCheckedChange={setAll}/>Оба этажа</label>}<button className="icon-button" title="Вернуть вид" onClick={reset}><RotateCcw size={17}/></button><button className="icon-button" title="Скачать изображение 3D" onClick={()=>{const r=runtime.current;if(!r)return;r.r.render(r.scene,r.camera);const a=document.createElement('a');a.download='BROADWAY-3D.png';a.href=r.r.domElement.toDataURL('image/png');a.click()}}><Camera size={17}/></button></div><div className="canvas-hint">Потяните для вращения · Колесо для приближения · Правая кнопка для перемещения</div></div>
}
